# Vorlage:
# https://medium.com/towards-data-engineering/running-a-postgresql-and-pgadmin4-instance-using-docker-compose-c6dd6e6e03bb
#
# Verbindung von pgadmin zu postgres muss manuell eingerichtet werden, siehe
# "5. Connecting to the Database server" im obigen Link

version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: datenbank-nutzer
      POSTGRES_PASSWORD: g3h3im
      POSTGRES_DB: meine_postgres_db

    # ACHTUNG: ohne Definition eines Volumes gehen die Daten verloren
    #          wenn der Container gelöscht wird
    # volumes:
    #   - "postgres-data:/var/lib/postgresql/data"

    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9.4.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pg-admin-nutzer@test.de
      PGADMIN_DEFAULT_PASSWORD: pg-admin-geheim
    ports:
      - "5050:80"