version: '3.8'


# Docker-Image f端r H2-Datenbank: https://github.com/oscarfonts/docker-h2
services:
  h2-db:
    image: oscarfonts/h2  # f端r neueste Version siehe https://hub.docker.com/r/oscarfonts/h2/tags
    container_name: h2-database
    ports:
      - "9092:1521"     # Port f端r JDBC-Verbindung
      - "9090:81"       # Port f端r Web-UI "H2 Console"
    environment:
      - H2_OPTIONS=-ifNotExists
#    volumes:
#      - h2-data:/opt/h2-data
    restart: unless-stopped

#volumes:
#  h2-data:
#    driver: local
